CREATE TABLE `OFICINA`(
	`ID_OFICINA` int AUTO_INCREMENT NOT NULL,
	`CNPJ` char(14) NOT NULL,
	`NOME_OFICINA` varchar(50) NOT NULL,
	`APELIDO` varchar(15) DEFAULT '' NOT NULL,
	`INSC_ESTADUAL` varchar(15) DEFAULT '' NOT NULL,
	`INSC_MUNICIPAL` varchar(15) DEFAULT '' NOT NULL,
	`CEP` char(8) DEFAULT '' NOT NULL,
	`LOGRADOURO` varchar(80) DEFAULT '' NOT NULL,
	`NUMERO` varchar(6) DEFAULT '' NULL,
	`COMPLEMENTO` varchar(30) DEFAULT '' NULL,
	`BAIRRO` varchar(40) DEFAULT '' NULL,
	`CIDADE` varchar(50) DEFAULT '' NULL,
	`TELEFONE1` varchar(11) DEFAULT '' NOT NULL,
	`TELEFONE2` varchar(11) DEFAULT '' NOT NULL,
	`EMAIL` varchar(155) DEFAULT '' NOT NULL,
	`EMAIL_NF` varchar(155) DEFAULT '' NOT NULL,
	`OPCAO_CADASTRO` bit DEFAULT 0 NOT NULL,
PRIMARY KEY (`ID_OFICINA`),
KEY `CNPJ` (`CNPJ`),
KEY `APELIDO` (`APELIDO`),
KEY `INSC_ESTADUAL` (`INSC_ESTADUAL`),
KEY `INSC_MUNICIPAL` (`INSC_MUNICIPAL`),
KEY `EMAIL` (`EMAIL`),
KEY `EMAIL_NF` (`EMAIL_NF`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de cadastro de oficinas';

CREATE TABLE `FUNCIONARIO`(
	`ID_FUNCIONARIO` int AUTO_INCREMENT NOT NULL,
	`NOME` varchar(70) NOT NULL,
	`FUNCAO` varchar(20) NOT NULL,
	`ID_OFICINA` int NOT NULL,
PRIMARY KEY (`ID_FUNCIONARIO`),
KEY `NOME` (`NOME`),
KEY `FUNCAO` (`FUNCAO`),
KEY `ID_OFICINA` (`ID_OFICINA`),
CONSTRAINT `FK_Funcionario_Oficina` FOREIGN KEY (`ID_OFICINA`) REFERENCES `OFICINA` (`ID_OFICINA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de funcionários';

CREATE TABLE `USUARIO`(
	`ID_USUARIO` int AUTO_INCREMENT NOT NULL,
	`ID_FUNCIONARIO` int NOT NULL,
	`LOGIN_USUARIO` varchar(50) NOT NULL,
	`SENHA_USUARIO` varchar(200) NOT NULL,
	`CLIENTE_OU_FUNCIONARIO` char(1) DEFAULT '' NOT NULL,
PRIMARY KEY (`ID_USUARIO`),
INDEX `ID_FUNCIONARIO` (`ID_FUNCIONARIO`),
INDEX `LOGIN_USUARIO` (`LOGIN_USUARIO`),
INDEX `SENHA_USUARIO` (`SENHA_USUARIO`),
CONSTRAINT `FK_Usuario_Funcionario` FOREIGN KEY (`ID_FUNCIONARIO`) REFERENCES `FUNCIONARIO` (`ID_FUNCIONARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de usuários';

CREATE TABLE `CLIENTE`(
	`ID_CLIENTE` int AUTO_INCREMENT NOT NULL,
	`CNPJ_CPF` varchar(14) NOT NULL,
	`NOME_CLIENTE` char(50) NOT NULL,
	`CNPJ_OU_CPF` char(1) NOT NULL,
	`APELIDO` varchar(15) DEFAULT '' NOT NULL,
	`DATA_NASCIMENTO` date DEFAULT '0000-00-00 00:00:00' NULL,
	`DATA_CADASTRO` datetime DEFAULT '0000-00-00 00:00:00' NULL,
	`ID_USUARIO_CAD` int NOT NULL,
	`EMAIL_NF` varchar(255) DEFAULT '' NULL,
	`CEP` char(8) DEFAULT '' NOT NULL,
	`LOGRADOURO` varchar(80) DEFAULT '' NOT NULL,
	`NUMERO` varchar(6) DEFAULT '' NOT NULL,
	`COMPLEMENTO` varchar(30) DEFAULT '' NOT NULL,
	`BAIRRO` varchar(40) DEFAULT '' NOT NULL,
	`CIDADE` varchar(50) DEFAULT '' NOT NULL,
	`TELEFONE` varchar(11) DEFAULT '' NULL,
	`CELULAR` varchar(11) DEFAULT '' NOT NULL,
PRIMARY KEY (`ID_CLIENTE`),
KEY (`CNPJ_CPF`),
KEY `EMAIL_NF` (`EMAIL_NF`),
KEY `ID_USUARIO_CAD` (`ID_USUARIO_CAD`),
KEY `CELULAR` (`CELULAR`),
KEY `APELIDO` (`APELIDO`),
KEY `DATA_NASCIMENTO` (`DATA_NASCIMENTO`),
CONSTRAINT `FK_Cliente_Usuario` FOREIGN KEY (`ID_USUARIO_CAD`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de cadastro de clientes';

CREATE TABLE `MARCA_CARRO`(
	`ID_MARCA` int AUTO_INCREMENT NOT NULL,
	`NOME_MARCA` varchar(30) NOT NULL,
PRIMARY KEY (`ID_MARCA`),
KEY `NOME_MARCA` (`NOME_MARCA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de lista de marcas de carros';

CREATE TABLE `MODELO_CARRO`(
	`ID_MODELO` int AUTO_INCREMENT NOT NULL,
	`ID_MARCA` int NOT NULL,
	`NOME_MODELO` varchar(30) NOT NULL,
PRIMARY KEY (`ID_MODELO`),
KEY `ID_MARCA` (`ID_MARCA`),
KEY `NOME_MODELO` (`NOME_MODELO`),
CONSTRAINT `FK_Modelo_Marca` FOREIGN KEY (`ID_MARCA`) REFERENCES `MARCA_CARRO` (`ID_MARCA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de lista de modelos de carros';

CREATE TABLE `VEICULO`(
	`ID_VEICULO` int AUTO_INCREMENT NOT NULL,
	`ID_MODELO` int NOT NULL,
	`PLACA_VEICULO` CHAR(7) NOT NULL,
	`MOTORIZACAO` varchar(5) NOT NULL,
	`ANO_FABRICACAO` char(4) NOT NULL,
	`ANO_MODELO` char(4) NOT NULL,
PRIMARY KEY (`ID_VEICULO`),
KEY `ID_MODELO` (`ID_MODELO`),
UNIQUE KEY `PLACA_VEICULO` (`PLACA_VEICULO`),
KEY `ANO_FABRICACAO` (`ANO_FABRICACAO`),
KEY `ANO_MODELO` (`ANO_MODELO`),
CONSTRAINT `FK_Veiculo_Modelo` FOREIGN KEY (`ID_MODELO`) REFERENCES `MODELO_CARRO` (`ID_MODELO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de cadastro de relação de veículos';

CREATE TABLE `CLIENTE_VEICULO`(
	`ID_CLI_VEICULO` int AUTO_INCREMENT NOT NULL,
	`ID_CLIENTE` int NOT NULL COMMENT 'Identificador do registro do cliente na tabela cliente.',
	`ID_VEICULO` int NOT NULL COMMENT 'Identificador do veículo do cliente. Chave estrangeira da tabela VEICULO',
	`VEICULO_ATUAL` bit NOT NULL COMMENT 'Identifica se o veículo cadastrado para o cliente é o atual',
	`DATA_CADASTRO` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
	`ID_USUARIO_CAD` int NOT NULL COMMENT 'Identifica o usuário que realizou o cadastrado',
PRIMARY KEY (`ID_CLI_VEICULO`),
KEY `ID_CLIENTE` (`ID_CLIENTE`),
KEY `ID_VEICULO` (`ID_VEICULO`),
KEY `ID_USUARIO_CAD` (`ID_USUARIO_CAD`),
CONSTRAINT `FK_ClienteVeiculo_Cliente` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_ClienteVeiculo_Veiculo` FOREIGN KEY (`ID_VEICULO`) REFERENCES `VEICULO` (`ID_VEICULO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_ClienteVeiculo_Usuario` FOREIGN KEY (`ID_USUARIO_CAD`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de cadastro de veículos dos clientes';

CREATE TABLE `ORDEM_SERVICO`(
	`ID_ORDEM_SERVICO` int AUTO_INCREMENT NOT NULL,
	`ID_CLIENTE` int NOT NULL,
	`ID_VEICULO` int NOT NULL,
	`DATA_ORDEM` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`TELEFONE_CONTATO` varchar(11) DEFAULT '' NOT NULL,
	`EMAIL_CONTATO` varchar(155) DEFAULT '' NOT NULL,
	`ID_OFICINA` int NOT NULL,
	`ID_AGENDAMENTO` int NULL,
	`ID_USUARIO_CAD` int NOT NULL,
PRIMARY KEY CLUSTERED (`ID_ORDEM_SERVICO`),
KEY `ID_CLIENTE` (`ID_CLIENTE`),
KEY `ID_VEICULO` (`ID_VEICULO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de ordens de serviços para o veículo do clliente';

CREATE TABLE `AGENDAMENTO_SERVICO` (
  `ID_AGENDAMENTO` int(11) NOT NULL,
  `ID_CLIENTE` int(11) DEFAULT NULL COMMENT 'Identificador do registro do cliente na tabela cliente.',
  `DATA_AGENDAMENTO` datetime DEFAULT NULL,
  `ID_CLIENTE_VEICULO` int(11) DEFAULT NULL COMMENT 'Identificador do veículo do cliente. Chave estrangeira da tabela CLIENTE_VEICULO',
  PRIMARY KEY (`ID_AGENDAMENTO`),
  UNIQUE KEY `ID_AGENDAMENTO_UNIQUE` (`ID_AGENDAMENTO`),
  KEY `ID_CLINETE` (`ID_CLIENTE`),
  KEY `ID_CLIENTE_VEICULO` (`ID_CLIENTE_VEICULO`),
  KEY `DATA_AGENDAMENTO` (`DATA_AGENDAMENTO`),
  CONSTRAINT `FK_Agendamento_Cliente` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_Agend_Cliente_Veiculo` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de agendamento de serviços para o veículo do clliente';

CREATE TABLE `SERVICO`(
	`ID_SERVICO` int AUTO_INCREMENT NOT NULL,
	`DESCRICAO` varchar(50) NOT NULL,
	`TEMPO_EXEC_SERVICO` time(6) NOT NULL,
	`CUSTO_HORA` numeric (5,2) NOT NULL,
PRIMARY KEY (`ID_SERVICO`),
KEY `DESCRICAO` (`DESCRICAO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de descrição de serviços para ser informada na tabela detalhe de ordem de serviços';

/* SCRIPT TABELA DETALHE_OS */
CREATE TABLE DETALHE_OS(
	`ID_DETALHE` int AUTO_INCREMENT NOT NULL,
	`ID_ORDEM` int NOT NULL,
	`ID_SERVICO` int NOT NULL,
	`ID_MEC_RESPONSAVEL` int NOT NULL,
	`QUANTIDADE` numeric(3) NOT NULL,
	`TEMPO_PREVISTO` time NOT NULL,
	`DATA_INICIO_SERVICO` datetime NOT NULL,
	`DATA_FIM_SERVICO` datetime NOT NULL,
	`APROVADO` bit NOT NULL,
	`VALOR_UNITARIO` float NOT NULL,
PRIMARY KEY (`ID_DETALHE`),
KEY `ID_ORDEM` (`ID_ORDEM`),
KEY `ID_SERVICO` (`ID_SERVICO`),
KEY `ID_MEC_RESPONSAVEL` (`ID_MEC_RESPONSAVEL`),
KEY `DATA_INICIO_SERVICO` (`DATA_INICIO_SERVICO`),
KEY `DATA_FIM_SERVICO` (`DATA_FIM_SERVICO`),
CONSTRAINT `FK_DetalheOS_Ordem` FOREIGN KEY (`ID_ORDEM`) REFERENCES `ORDEM_SERVICO` (`ID_ORDEM_SERVICO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_DetalheOS_Servico` FOREIGN KEY (`ID_SERVICO`) REFERENCES `SERVICO` (`ID_SERVICO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_DetalheOS_Mec_Resp` FOREIGN KEY (`ID_MEC_RESPONSAVEL`) REFERENCES `FUNCIONARIO` (`ID_FUNCIONARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Tabela de detalhamento de serviços para o veículo do clliente';


